from typing import Tuple
from app.core.planner import ActionPlan, ActionType
from app.core.domain_validator import DomainValidator, DomainValidationError
from app.core.audit_logger import audit_logger

class SafetyThresholds:
    MIN_NAVIGATION_CONFIDENCE = 0.80
    MIN_FIELD_CONFIDENCE = 0.85
    MIN_SUBMISSION_CONFIDENCE = 0.90
    MIN_SUCCESS_DETECTION_CONFIDENCE = 0.85

class ActionSafetyViolation(Exception):
    """Raised when an automated action violates security boundaries."""
    pass

class SafetyValidator:
    """
    Validates every action generated by the planner before execution.
    Enforces confidence thresholds, domain boundaries, and human approval rules.
    """

    def __init__(self):
        self.domain_validator = DomainValidator()

    def validate_action(self, action: ActionPlan, current_service: str, current_domain: str) -> Tuple[bool, str]:
        """
        Validates safety of the planned action.
        Returns (True, "OK") if safe, or (False, reason) if unsafe/rejected.
        """
        if action.action_type == ActionType.HALT:
            return False, action.reason

        # 1. Navigation validation
        if action.action_type == ActionType.NAVIGATE:
            if action.confidence < SafetyThresholds.MIN_NAVIGATION_CONFIDENCE:
                return False, f"Navigation confidence ({action.confidence:.2f}) is below minimum threshold ({SafetyThresholds.MIN_NAVIGATION_CONFIDENCE:.2f})."
            if action.target_url:
                try:
                    self.domain_validator.validate_url(action.target_url, current_service)
                except DomainValidationError as e:
                    return False, f"Navigation domain security violation: {str(e)}"

        # 2. Field fill validation
        elif action.action_type == ActionType.FILL:
            if action.confidence < SafetyThresholds.MIN_FIELD_CONFIDENCE:
                return False, f"Password field confidence ({action.confidence:.2f}) for '{action.field_role}' is below safety threshold ({SafetyThresholds.MIN_FIELD_CONFIDENCE:.2f}). Never guessing."

        # 3. Submission validation
        elif action.action_type == ActionType.SUBMIT:
            if action.confidence < SafetyThresholds.MIN_SUBMISSION_CONFIDENCE:
                return False, f"Submission button confidence ({action.confidence:.2f}) is below safety threshold ({SafetyThresholds.MIN_SUBMISSION_CONFIDENCE:.2f})."
            if not action.requires_human_approval:
                return False, "Password change submission MUST require explicit human confirmation."

        # 4. Human takeover actions are inherently safe to trigger
        elif action.action_type == ActionType.WAIT_FOR_HUMAN:
            return True, "Human takeover required."

        return True, "Action approved by Safety Validator."
